"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabaseBrowser";

type Property = { id: string; name: string };
type Task = { id: string; property_id: string; conversation_id: string | null; title: string; status: "open" | "completed"; due_at: string | null; created_at: string };
function dueLabel(value: string | null) { if (!value) return "No due date"; const date = new Date(value); if (Number.isNaN(date.getTime())) return "No due date"; return date.getTime() < Date.now() ? "Overdue" : `Due ${date.toLocaleDateString()}`; }

export default function TasksClient({ properties }: { properties: Property[] }) {
  const client = useMemo(() => getSupabaseBrowserClient(), []); const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showCompleted, setShowCompleted] = useState(false); const [propertyFilter, setPropertyFilter] = useState("all"); const [busy, setBusy] = useState<string | null>(null);
  const headers = useCallback(async () => { const { data } = await client.auth.getSession(); if (!data.session?.access_token) throw new Error("Please sign in again."); return { Authorization: `Bearer ${data.session.access_token}`, "Content-Type": "application/json" }; }, [client]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const auth = await headers(); const results = await Promise.all(properties.map(async (property) => { const response = await fetch(`/api/tasks?propertyId=${property.id}`, { headers: auth }); if (!response.ok) throw new Error("Unable to load follow-ups"); return await response.json() as Task[]; })); setTasks(results.flat().sort((a, b) => Number(a.status === "completed") - Number(b.status === "completed") || (a.due_at ?? "9999").localeCompare(b.due_at ?? "9999") || b.created_at.localeCompare(a.created_at))); } catch (e: any) { setError(e.message ?? "Unable to load follow-ups"); } finally { setLoading(false); } }, [headers, properties]);
  useEffect(() => { void load(); }, [load]);
  async function toggle(task: Task) { setBusy(task.id); try { const response = await fetch(`/api/tasks/${task.id}`, { method: "PATCH", headers: await headers(), body: JSON.stringify({ property_id: task.property_id, status: task.status === "open" ? "completed" : "open" }) }); if (!response.ok) throw new Error("Unable to update follow-up"); const updated = await response.json(); setTasks((current) => current.map((item) => item.id === task.id ? updated : item)); } catch (e: any) { setError(e.message ?? "Unable to update follow-up"); } finally { setBusy(null); } }
  const visible = tasks.filter((task) => (showCompleted || task.status === "open") && (propertyFilter === "all" || task.property_id === propertyFilter)); const propertyName = (id: string) => properties.find((p) => p.id === id)?.name ?? "Property";
  return <><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", gap: 10, marginBottom: 14, flexWrap: "wrap" }}><span style={{ color: "#475569", fontSize: 13 }}>{visible.length} {showCompleted ? "tasks" : "open tasks"}</span><label style={{ display: "grid", gap: 4, fontSize: 12, color: "#475569" }}>House<select value={propertyFilter} onChange={(e) => setPropertyFilter(e.target.value)} style={{ padding: "6px 8px", border: "1px solid #cbd5e1", borderRadius: 7, background: "#fff" }}><option value="all">All houses</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.name}</option>)}</select></label><label style={{ fontSize: 13 }}><input type="checkbox" checked={showCompleted} onChange={(e) => setShowCompleted(e.target.checked)} /> Show completed</label></div>{error ? <p role="alert" style={{ color: "#b91c1c" }}>{error}</p> : null}{loading ? <p>Loading follow-ups…</p> : null}{!loading && !visible.length ? <p style={{ color: "#64748b" }}>No follow-ups here.</p> : null}<div style={{ display: "grid", gap: 8 }}>{visible.map((task) => <article key={task.id} style={{ border: "1px solid #dbe4ee", borderRadius: 10, padding: 12, display: "flex", gap: 10, alignItems: "center", background: task.status === "completed" ? "#f8fafc" : "#fff" }}><input type="checkbox" checked={task.status === "completed"} disabled={busy === task.id} onChange={() => void toggle(task)} /><div style={{ flex: 1 }}><div style={{ textDecoration: task.status === "completed" ? "line-through" : "none", fontWeight: 600 }}>{task.title}</div><small style={{ color: task.status === "open" && dueLabel(task.due_at) === "Overdue" ? "#c2410c" : "#64748b" }}>{propertyName(task.property_id)} · {dueLabel(task.due_at)}</small></div>{task.conversation_id ? <Link href={`/dashboard/conversations/${task.conversation_id}`} style={{ fontSize: 13 }}>Open thread</Link> : null}</article>)}</div></>;
}
