"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabaseBrowser";

type Property = { id: string; name: string };
type Issue = { id: string; property_id: string; conversation_id: string | null; title: string; description: string | null; category: string; priority: "low" | "normal" | "high" | "urgent"; status: "open" | "in_progress" | "resolved" | "closed"; occurrence_count: number; first_reported_at: string; last_reported_at: string };
const field: React.CSSProperties = { padding: "8px 9px", border: "1px solid #cbd5e1", borderRadius: 7, background: "#fff", minWidth: 0 };
const button: React.CSSProperties = { padding: "8px 11px", border: 0, borderRadius: 7, background: "#155eef", color: "#fff", fontWeight: 600, cursor: "pointer" };
const categories = ["general", "hvac", "plumbing", "electrical", "appliance", "lock_access", "damage", "pest", "cleaning", "safety"] as const;

function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()); }
function priorityStyle(value: Issue["priority"]) { return value === "urgent" ? { color: "#b91c1c", background: "#fef2f2", borderColor: "#fecaca" } : value === "high" ? { color: "#c2410c", background: "#fff7ed", borderColor: "#fed7aa" } : { color: "#475569", background: "#f8fafc", borderColor: "#cbd5e1" }; }

export default function MaintenanceClient({ properties }: { properties: Property[] }) {
  const client = useMemo(() => getSupabaseBrowserClient(), []); const [issues, setIssues] = useState<Issue[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [propertyId, setPropertyId] = useState(() => properties[0]?.id ?? ""); const [filterProperty, setFilterProperty] = useState("all"); const [filterStatus, setFilterStatus] = useState("open"); const [search, setSearch] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState<string>("general"); const [priority, setPriority] = useState<Issue["priority"]>("normal"); const [recurrenceKey, setRecurrenceKey] = useState(""); const [saving, setSaving] = useState(false); const [busy, setBusy] = useState<string | null>(null);
  const headers = useCallback(async () => { const { data } = await client.auth.getSession(); if (!data.session?.access_token) throw new Error("Please sign in again."); return { Authorization: `Bearer ${data.session.access_token}`, "Content-Type": "application/json" }; }, [client]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const auth = await headers(); const all = await Promise.all(properties.map(async (property) => { const r = await fetch(`/api/maintenance?property_id=${property.id}`, { headers: auth }); const payload = await r.json(); if (!r.ok) throw new Error(payload?.error ?? "Unable to load maintenance issues"); return payload as Issue[]; })); setIssues(all.flat().sort((a, b) => Number(["open", "in_progress"].includes(b.status)) - Number(["open", "in_progress"].includes(a.status)) || b.last_reported_at.localeCompare(a.last_reported_at))); } catch (e: any) { setError(e?.message ?? "Unable to load maintenance issues"); } finally { setLoading(false); } }, [headers, properties]);
  useEffect(() => { void load(); }, [load]);
  async function add(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || !propertyId) return; setSaving(true); setError(null); try { const r = await fetch("/api/maintenance", { method: "POST", headers: await headers(), body: JSON.stringify({ property_id: propertyId, title, description, category, priority, recurrence_key: recurrenceKey }) }); const data = await r.json(); if (!r.ok) throw new Error(data?.error ?? "Unable to log issue"); setIssues((current) => [data.issue, ...current.filter((item) => item.id !== data.issue.id)]); setTitle(""); setDescription(""); setCategory("general"); setPriority("normal"); setRecurrenceKey(""); } catch (e: any) { setError(e?.message ?? "Unable to log issue"); } finally { setSaving(false); } }
  async function changeStatus(issue: Issue, status: Issue["status"]) { setBusy(issue.id); setError(null); try { const r = await fetch(`/api/maintenance/${issue.id}`, { method: "PATCH", headers: await headers(), body: JSON.stringify({ property_id: issue.property_id, status }) }); const data = await r.json(); if (!r.ok) throw new Error(data?.error ?? "Unable to update issue"); setIssues((current) => current.map((item) => item.id === issue.id ? data : item)); } catch (e: any) { setError(e?.message ?? "Unable to update issue"); } finally { setBusy(null); } }
  const visible = issues.filter((item) => (filterProperty === "all" || item.property_id === filterProperty) && (filterStatus === "all" || item.status === filterStatus) && (!search.trim() || `${item.title}\n${item.description ?? ""}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))); const propertyName = (id: string) => properties.find((p) => p.id === id)?.name ?? "Property";
  return <>
    <form onSubmit={add} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(165px, 1fr))", gap: 8, padding: 13, border: "1px solid #dbe4ee", borderRadius: 11, background: "#f8fafc", marginBottom: 18 }}><input value={title} onChange={(e) => setTitle(e.target.value)} required maxLength={280} placeholder="Log issue, e.g. AC not cooling" style={field} /><select value={propertyId} onChange={(e) => setPropertyId(e.target.value)} style={field}>{properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={category} onChange={(e) => setCategory(e.target.value)} style={field}>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><select value={priority} onChange={(e) => setPriority(e.target.value as Issue["priority"])} style={field}><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option><option value="urgent">Urgent</option></select><input value={recurrenceKey} onChange={(e) => setRecurrenceKey(e.target.value)} placeholder="Repeat identifier (optional)" maxLength={160} style={field} /><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What happened, where, and any troubleshooting…" maxLength={6000} rows={2} style={{ ...field, resize: "vertical" }} /><button type="submit" disabled={saving || !propertyId || !title.trim()} style={button}>{saving ? "Logging…" : "Log maintenance issue"}</button></form>
    <div style={{ display: "flex", gap: 8, alignItems: "end", flexWrap: "wrap", marginBottom: 14 }}><label style={{ display: "grid", gap: 4, fontSize: 12 }}>House<select value={filterProperty} onChange={(e) => setFilterProperty(e.target.value)} style={field}><option value="all">All houses</option>{properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label style={{ display: "grid", gap: 4, fontSize: 12 }}>Status<select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} style={field}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option><option value="all">All statuses</option></select></label><label style={{ display: "grid", gap: 4, flex: "1 1 230px", fontSize: 12 }}>Search issues<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name or details…" style={field} /></label></div>
    {error ? <p role="alert" style={{ color: "#b91c1c" }}>{error}</p> : null}{loading ? <p>Loading maintenance issues…</p> : null}{!loading && !visible.length ? <p style={{ color: "#64748b" }}>No matching maintenance issues.</p> : null}
    <div style={{ display: "grid", gap: 8 }}>{visible.map((issue) => <article key={issue.id} style={{ border: "1px solid #dbe4ee", borderRadius: 10, padding: 12, background: "#fff" }}><div style={{ display: "flex", gap: 8, alignItems: "start", justifyContent: "space-between", flexWrap: "wrap" }}><div><strong>{issue.title}</strong><div style={{ color: "#64748b", fontSize: 12, marginTop: 3 }}>{propertyName(issue.property_id)} · {label(issue.category)} · Last reported {new Date(issue.last_reported_at).toLocaleDateString()}</div></div><span style={{ ...priorityStyle(issue.priority), border: "1px solid", borderRadius: 999, padding: "3px 7px", fontSize: 11, fontWeight: 650 }}>{label(issue.priority)}</span></div>{issue.description ? <p style={{ whiteSpace: "pre-wrap", color: "#475569", margin: "8px 0", fontSize: 13 }}>{issue.description}</p> : null}<div style={{ display: "flex", gap: 7, alignItems: "center", flexWrap: "wrap" }}><span style={{ fontSize: 12, color: "#475569" }}>{issue.occurrence_count > 1 ? `Reported ${issue.occurrence_count} times` : label(issue.status)}</span>{issue.status === "open" ? <button type="button" disabled={busy === issue.id} onClick={() => void changeStatus(issue, "in_progress")} style={quiet}>Start work</button> : null}{["open", "in_progress"].includes(issue.status) ? <button type="button" disabled={busy === issue.id} onClick={() => void changeStatus(issue, "resolved")} style={quiet}>Mark resolved</button> : null}{issue.conversation_id ? <Link href={`/dashboard/conversations/${issue.conversation_id}`} style={{ fontSize: 12 }}>Open guest conversation</Link> : null}</div></article>)}</div>
  </>;
}
const quiet: React.CSSProperties = { padding: "5px 7px", border: "1px solid #cbd5e1", borderRadius: 6, background: "#fff", color: "#334155", fontSize: 12, cursor: "pointer" };
